version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ~/docker_data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ~/docker_data/pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  mongodb:
    image: mongo:latest
    env_file:
      - docker.env
    ports:
      - 27017:27017

networks:
  postgres:
    driver: bridge
